### ISSUE TITLE
Process running mem=948M(185.2%) Error R14 (Memory quota exceeded)

### ISSUE THREAD

**Issue by Samuelngala3** [DGXeon/CheemsBot-MD3#9]
2022-06-26T23:34:01.194564+00:00 app[worker.1]: 0|index  |     at runMicrotasks (<anonymous>)
2022-06-26T23:34:01.194568+00:00 app[worker.1]: 0|index  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-06-26T23:34:01.194579+00:00 app[worker.1]: 0|index  |     at Object.generateWAMessageContent (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:175:16)
2022-06-26T23:34:01.194590+00:00 app[worker.1]: 0|index  |     at Object.generateWAMessage (/app/node_modules/@adiwajshing/baileys/lib/Utils/messages.js:349:68)
2022-06-26T23:34:01.194600+00:00 app[worker.1]: 0|index  |     at Object.sendMessage (/app/node_modules/@adiwajshing/baileys/lib/Socket/messages-send.js:397:47)
2022-06-26T23:34:01.194617+00:00 app[worker.1]: 0|index  |     at XeonBotInc (/app/XeonCheems3.js:11037:12)
2022-06-26T23:34:01.194622+00:00 app[worker.1]: 0|index  |     at runMicrotasks (<anonymous>)
2022-06-26T23:34:01.194633+00:00 app[worker.1]: 0|index  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-06-26T23:34:02.498625+00:00 heroku[worker.1]: Process running mem=855M(167.0%)
2022-06-26T23:34:02.500382+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:34:23.740694+00:00 heroku[worker.1]: Process running mem=823M(160.9%)
2022-06-26T23:34:23.744736+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:34:44.759401+00:00 heroku[worker.1]: Process running mem=827M(161.6%)
2022-06-26T23:34:44.782426+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:35:05.507715+00:00 heroku[worker.1]: Process running mem=829M(162.1%)
2022-06-26T23:35:05.509219+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:35:26.616380+00:00 heroku[worker.1]: Process running mem=830M(162.1%)
2022-06-26T23:35:26.617755+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:35:47.413042+00:00 heroku[worker.1]: Process running mem=829M(162.1%)
2022-06-26T23:35:47.414574+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:36:08.600258+00:00 heroku[worker.1]: Process running mem=832M(162.5%)
2022-06-26T23:36:08.603538+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:36:29.397547+00:00 heroku[worker.1]: Process running mem=830M(162.1%)
2022-06-26T23:36:29.399773+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:36:50.638124+00:00 heroku[worker.1]: Process running mem=831M(162.5%)
2022-06-26T23:36:50.639709+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:37:11.798413+00:00 heroku[worker.1]: Process running mem=830M(162.2%)
2022-06-26T23:37:11.799872+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:37:32.623550+00:00 heroku[worker.1]: Process running mem=839M(164.0%)
2022-06-26T23:37:32.626445+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:37:53.624702+00:00 heroku[worker.1]: Process running mem=840M(164.2%)
2022-06-26T23:37:53.625917+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:38:14.475590+00:00 heroku[worker.1]: Process running mem=841M(164.3%)
2022-06-26T23:38:14.476881+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:38:35.654160+00:00 heroku[worker.1]: Process running mem=841M(164.3%)
2022-06-26T23:38:35.657330+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:38:56.523746+00:00 heroku[worker.1]: Process running mem=840M(164.2%)
2022-06-26T23:38:56.527112+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:39:17.732165+00:00 heroku[worker.1]: Process running mem=865M(169.0%)
2022-06-26T23:39:17.734090+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:39:38.459383+00:00 heroku[worker.1]: Process running mem=947M(185.1%)
2022-06-26T23:39:38.461163+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)
2022-06-26T23:39:59.585701+00:00 heroku[worker.1]: Process running mem=948M(185.2%)
2022-06-26T23:39:59.586975+00:00 heroku[worker.1]: Error R14 (Memory quota exceeded)

**Comment by Alien-alfa** [comment]
Yea this happens cuz Heroku free accounts has a small amount of resources. Just restart the app and it will reset.
